### ISSUE TITLE
No mention of issues with SDFormatter and 64GB SD cards

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/software-guide#13]
As prices of microSD cards continue to fall, I guess more and more people are likely to attempt to use a 64GB (or larger) SD card with NOOBS.
However as explained [here](https://www.raspberrypi.org/documentation/installation/sdxc_formatting.md) there's some issues to be aware of when trying to use a 64GB microSD card with NOOBS.

The NOOBS instructions at https://www.raspberrypi.org/learning/software-guide/quickstart/ just say to use the SD Formatter tool. However anyone doing so with a 64GB (or larger) SD card will then end up with their card formatted as exFAT, and the Raspberry Pi isn't able to boot from cards that are formatted as exFAT. So the user following those NOOBS instructions will then have absolutely no idea why NOOBS is failing to boot on their Pi if they happen to be using a 64GB card.

The simplest way of 'fixing' this issue would be to add a link to https://www.raspberrypi.org/documentation/installation/sdxc_formatting.md from https://www.raspberrypi.org/learning/software-guide/quickstart/

**Comment by lawsie** [comment]
Thanks, this will be fixed by #14 once it's been copy edited.

**Comment by lurch** [comment]
Great, thank @lawsie :+1: 
Strictly speaking, exFAT is incompatible with the Raspberry Pi, rather than just NOOBS specifically; but the text that you have there currently is fine :)
