### ISSUE TITLE
broken image link

### ISSUE THREAD

**Issue by Dan-himself** [raspberrypilearning/software-guide#2]
On /backup, Section 2, step 5
![backup files](https://cloud.githubusercontent.com/assets/18287886/15250963/295f7474-191f-11e6-829e-fb5cd565137b.JPG)

**Comment by LornaLynch** [comment]
Sorry to ask, @MarcScott, but should this be a link to winscp1.png, or is the file missing? I wasn't sure.

**Comment by MarcScott** [comment]
@LornaLynch @Dan-himself It's that same missing image from the other resource. I'll try and grab the file today.

**Comment by LornaLynch** [comment]
D'oh! Thanks, @MarcScott.

**Comment by MarcScott** [comment]
added now
