### ISSUE TITLE
copyedit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/software-guide#3]
Hi @LornaLynch and @lauraclay,
Could I get a copy edit please?
Thanks

**Comment by LornaLynch** [comment]
In backup.md, the first two links at the foot of the document (Installing Rasbpian and Quick Start Guide) weren't working. I made them point at quickstart.md, as that seemed to be what was intended, but please check them to be sure.

**Comment by LornaLynch** [comment]
In quickstart.md, the links to the Hardward document aren't working, but I guess we can't fix this until it goes live?

**Comment by LornaLynch** [comment]
Done apart from the points above.

**Comment by MissPhilbin** [comment]
@LornaLynch Would you mind taking another look over this repo. I've found typos in some of the files. These may have been introduced after your last pass. Thanks.

**Comment by LornaLynch** [comment]
Sure, @MissPhilbin: I'll have a look now.

**Comment by LornaLynch** [comment]
Query - quickstart.md is currently titled "Raspberry Pi Software Guide", but all the linked pages refer to it as "Quick Start Guide". For consistency's sake, do we want the title to be "Software Guide", "Quick Start Guide", or "Software Quick Start Guide"?

**Comment by MissPhilbin** [comment]
'Raspberry Pi Software Guide' please.

On Tue, Jul 12, 2016 at 10:24 AM, Lorna Lynch notifications@github.com
wrote:

> Query - quickstart.md is currently titled "Raspberry Pi Software Guide",
> but all the linked pages refer to it as "Quick Start Guide". Do we want the
> title to be "Software Guide", "Quick Start Guide", or "Software Quick Start
> Guide"?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/raspberrypilearning/software-guide/issues/3#issuecomment-231985584,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACWT-S7urC6zndrmBDiV5LVFlYIaelReks5qU11ogaJpZM4I1OSs
> .

## 

Director of Education
Raspberry Pi Foundation
UK Charity No. 1129409

www.raspberrypi.org | www.codeclub.org.uk
@ http://twitter.com/missphilbin | in
https://uk.linkedin.com/in/carrie-anne-philbin-a20649b7 | _▷_
https://www.youtube.com/user/GeekGurlDiaries

**Comment by LornaLynch** [comment]
Thanks!

**Comment by LornaLynch** [comment]
Done, @MissPhilbin :)

**Comment by MissPhilbin** [comment]
Thank you!

On Tue, Jul 12, 2016 at 12:10 PM, Lorna Lynch notifications@github.com
wrote:

> Done, @MissPhilbin https://github.com/MissPhilbin :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/raspberrypilearning/software-guide/issues/3#issuecomment-232009247,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACWT-aTljC9KKAi5lfhgbzM0fS_tGxwOks5qU3YTgaJpZM4I1OSs
> .

## 

Director of Education
Raspberry Pi Foundation
UK Charity No. 1129409

www.raspberrypi.org | www.codeclub.org.uk
@ http://twitter.com/missphilbin | in
https://uk.linkedin.com/in/carrie-anne-philbin-a20649b7 | _▷_
https://www.youtube.com/user/GeekGurlDiaries
