### ISSUE TITLE
Use unpixeled Github link image

### ISSUE THREAD

**Issue by niccokunzmann** [raspberrypilearning/software-guide#5]
I use images in my blog which you can use. License is CC0

- [round](https://github.com/niccokunzmann/niccokunzmann.github.io/blob/master/images/footer/GitHub.svg)
- [edgy](https://github.com/niccokunzmann/niccokunzmann.github.io/blob/master/images/home_links/GitHub.svg)

Regards.
PS: if you need a Pull-Request, guide me.

**Comment by bennuttall** [comment]
Sorry - use it for what?

**Comment by niccokunzmann** [comment]
It is alright. At the bottom, you have a link to Github, to this repository. This link is an image. This image is a png with pixels. It is scaled bigger, so I see the pixels. I suggest to use the svg as a replacement for this image. The SVG does not have big pixels.

**Comment by bennuttall** [comment]
Oh I see, I'll make a note. It's not related to this repository though (a specific learning resource).

Thanks

**Comment by niccokunzmann** [comment]
@bennuttall I will wait for your note, then : )
