### ISSUE TITLE
Broken link in wifi.md

### ISSUE THREAD

**Issue by DrGFreeman** [raspberrypilearning/software-guide#7]
Hello,

While browsing the Software Guide, I noticed a broken link in the wifi.md file. The link to Raspberry Pi Software Guide in "What's next" section is pointing to "worksheet.md" instead of "quickstart.md".

I submitted PR #6 to fix this link.

Cheers!

DrGFreeman

**Comment by lawsie** [comment]
Thank you :) Now merged.
